using System;
using Newtonsoft.Json;

namespace Jellyfin.Plugin.Streamyfin.Db;

/// <summary>
/// An Expo push token for one device a user is signed in to.
/// </summary>
/// <remarks>
/// This type is both the stored entity and the shape the API accepts and returns,
/// which is why it carries the Newtonsoft attributes. Renaming a property renames
/// a column and changes the wire format at the same time.
/// </remarks>
public class DeviceToken
{
    /// <summary>
    /// Gets or sets the Expo push token.
    /// </summary>
    [JsonProperty(PropertyName = "token")]
    public string Token { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the device id generated by the app. One token per device.
    /// </summary>
    [JsonProperty(PropertyName = "deviceId")]
    public Guid DeviceId { get; set; }

    /// <summary>
    /// Gets or sets the Jellyfin user the device is signed in as.
    /// </summary>
    [JsonProperty(PropertyName = "userId")]
    public Guid UserId { get; set; }

    /// <summary>
    /// Gets or sets when the token was last registered, as a Windows file time.
    /// </summary>
    /// <remarks>
    /// File time rather than Unix time because that is what the hand written store
    /// wrote, and changing it would reinterpret every imported row.
    /// </remarks>
    [JsonProperty(PropertyName = "timestamp")]
    public long Timestamp { get; set; }
}
