using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Jellyfin.Plugin.Streamyfin.Configuration.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Jellyfin.Plugin.Streamyfin.Db;

/// <summary>
/// The plugin's persistence, over EF Core.
/// </summary>
/// <remarks>
/// A context is created per operation rather than held. Contexts are cheap, and
/// a short lived one keeps the change tracker from growing and removes the need
/// for the reader writer lock the hand written store carried.
/// </remarks>
public class PluginDatabase
{
    /// <summary>
    /// The database written by the hand written SQLite store this replaces.
    /// It is read once and then left alone, so downgrading still finds its data.
    /// </summary>
    internal const string LegacyFileName = "streamyfin_plugin.db";

    private const string FileName = "streamyfin.db";

    private readonly ILogger<PluginDatabase>? _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="PluginDatabase"/> class, applying
    /// migrations and running any pending one time import.
    /// </summary>
    /// <param name="path">Directory the database lives in.</param>
    /// <param name="logger">Optional logger.</param>
    public PluginDatabase(string path, ILogger<PluginDatabase>? logger = null)
    {
        ArgumentNullException.ThrowIfNull(path);

        _logger = logger;
        Directory.CreateDirectory(path);
        DbFilePath = Path.Combine(path, FileName);
        LegacyDbFilePath = Path.Combine(path, LegacyFileName);

        using var context = CreateContext();
        context.Database.Migrate();

        ImportLegacyDeviceTokens(context);
    }

    /// <summary>
    /// Gets the full path of the database file.
    /// </summary>
    public string DbFilePath { get; }

    /// <summary>
    /// Gets the full path of the database this one replaced.
    /// </summary>
    internal string LegacyDbFilePath { get; }

    /// <summary>
    /// Creates a context against this database.
    /// </summary>
    /// <returns>A new context the caller owns.</returns>
    public StreamyfinDbContext CreateContext() => new(DbFilePath);

    /// <summary>
    /// Gets the push tokens for every device a user is currently signed in on.
    /// </summary>
    /// <param name="userId">Jellyfin user id.</param>
    /// <returns>The user's device tokens.</returns>
    public List<DeviceToken> GetUserDeviceTokens(Guid userId)
    {
        using var context = CreateContext();
        return context.DeviceTokens.AsNoTracking()
            .Where(t => t.UserId == userId)
            .ToList();
    }

    /// <summary>
    /// Gets every known device token.
    /// </summary>
    /// <returns>All device tokens.</returns>
    public List<DeviceToken> GetAllDeviceTokens()
    {
        using var context = CreateContext();
        return context.DeviceTokens.AsNoTracking().ToList();
    }

    /// <summary>
    /// Gets the token registered for one device.
    /// </summary>
    /// <param name="deviceId">Device id generated by the app.</param>
    /// <returns>The token, or <c>null</c> when the device is unknown.</returns>
    public DeviceToken? GetDeviceTokenForDeviceId(Guid deviceId)
    {
        using var context = CreateContext();
        return context.DeviceTokens.AsNoTracking()
            .FirstOrDefault(t => t.DeviceId == deviceId);
    }

    /// <summary>
    /// Registers a token for a device, replacing whatever that device had before.
    /// </summary>
    /// <param name="token">The token to store. Its timestamp is set here.</param>
    /// <returns>The stored token, with its timestamp.</returns>
    public DeviceToken AddDeviceToken(DeviceToken token)
    {
        ArgumentNullException.ThrowIfNull(token);

        using var context = CreateContext();

        var timestamp = DateTime.UtcNow.ToFileTime();

        // One statement, so two registrations of the same device cannot race each
        // other. The app posts its token twice on sign in, and a lookup followed by an
        // insert let the second one fail on the device id with a 500 while the first
        // was still saving. An existing row is updated in place, never removed and
        // re-added, so a device is never left without a token between two writes.
        context.Database.ExecuteSqlInterpolated($"""
            INSERT INTO DeviceTokens (DeviceId, Token, UserId, Timestamp)
            VALUES ({token.DeviceId}, {token.Token}, {token.UserId}, {timestamp})
            ON CONFLICT(DeviceId) DO UPDATE SET
                Token = excluded.Token,
                UserId = excluded.UserId,
                Timestamp = excluded.Timestamp
            """);

        token.Timestamp = timestamp;
        return token;
    }

    /// <summary>
    /// Counts the registered devices.
    /// </summary>
    /// <returns>How many device tokens are stored.</returns>
    public long TotalDevicesCount()
    {
        using var context = CreateContext();
        return context.DeviceTokens.LongCount();
    }

    /// <summary>
    /// Forgets a device.
    /// </summary>
    /// <param name="deviceId">Device id generated by the app.</param>
    public void RemoveDeviceToken(Guid deviceId)
    {
        using var context = CreateContext();

        var existing = context.DeviceTokens.FirstOrDefault(t => t.DeviceId == deviceId);
        if (existing is null)
        {
            return;
        }

        context.DeviceTokens.Remove(existing);
        context.SaveChanges();
    }

    /// <summary>
    /// Forgets every device registered under a token Expo has reported as gone.
    /// </summary>
    /// <param name="tokens">The dead Expo push tokens.</param>
    /// <returns>How many device rows were removed.</returns>
    /// <remarks>
    /// By token rather than by device id, because that is the only thing Expo names. One
    /// token can sit on more than one row if a device re-registered under a new id
    /// without the old row ever being cleaned up, which is the very accumulation this
    /// removes, so every match goes.
    /// </remarks>
    public int RemoveDeviceTokensNamed(IEnumerable<string> tokens)
    {
        ArgumentNullException.ThrowIfNull(tokens);

        var dead = tokens.Distinct(StringComparer.Ordinal).ToList();
        if (dead.Count == 0)
        {
            return 0;
        }

        using var context = CreateContext();

        var rows = context.DeviceTokens.Where(t => dead.Contains(t.Token)).ToList();
        if (rows.Count == 0)
        {
            return 0;
        }

        context.DeviceTokens.RemoveRange(rows);
        context.SaveChanges();

        return rows.Count;
    }

    /// <summary>
    /// Remembers the pushes Expo accepted, so their receipts can be asked for later.
    /// </summary>
    /// <param name="receipts">The ticket and token pairs.</param>
    /// <param name="now">When the send happened, in UTC.</param>
    /// <remarks>
    /// A ticket id already stored is skipped rather than replaced. Expo does not reissue
    /// them, so a collision would mean something is wrong upstream and the first row is
    /// the one that knows which token it belonged to.
    /// </remarks>
    public void AddExpoReceipts(IEnumerable<(string TicketId, string Token)> receipts, DateTime now)
    {
        ArgumentNullException.ThrowIfNull(receipts);

        var incoming = receipts.ToList();
        if (incoming.Count == 0)
        {
            return;
        }

        using var context = CreateContext();

        var ids = incoming.Select(r => r.TicketId).ToList();
        var known = context.ExpoReceipts
            .Where(r => ids.Contains(r.TicketId))
            .Select(r => r.TicketId)
            .ToHashSet(StringComparer.Ordinal);

        var rows = incoming
            .Where(r => known.Add(r.TicketId))
            .Select(r => new ExpoReceipt { TicketId = r.TicketId, Token = r.Token, CreatedAt = now })
            .ToList();

        if (rows.Count == 0)
        {
            return;
        }

        context.ExpoReceipts.AddRange(rows);
        context.SaveChanges();
    }

    /// <summary>
    /// The pushes old enough for Expo to have produced a receipt.
    /// </summary>
    /// <param name="sentBefore">Only pushes older than this, in UTC.</param>
    /// <param name="limit">At most this many, since Expo takes 1000 ids per request.</param>
    /// <param name="excluding">Ticket ids to skip, typically the ones already asked about.</param>
    /// <returns>The oldest ones first.</returns>
    /// <remarks>
    /// The exclusion belongs in the query rather than in the caller, and that is not a
    /// preference. A push Expo has not resolved keeps its row, so filtering after the
    /// limit hands back the same oldest batch every time: a run whose first batch went
    /// entirely unanswered would take that batch, filter it away, find nothing new and
    /// stop, and everything behind it would wait for those rows to resolve or expire.
    /// Excluding before the limit is what lets a backlog actually be walked.
    /// </remarks>
    public List<ExpoReceipt> GetExpoReceiptsSentBefore(
        DateTime sentBefore,
        int limit,
        IReadOnlyCollection<string>? excluding = null)
    {
        using var context = CreateContext();

        var query = context.ExpoReceipts.AsNoTracking()
            .Where(r => r.CreatedAt <= sentBefore);

        if (excluding is { Count: > 0 })
        {
            query = query.Where(r => !excluding.Contains(r.TicketId));
        }

        return query
            .OrderBy(r => r.CreatedAt)
            .ThenBy(r => r.TicketId)
            .Take(limit)
            .ToList();
    }

    /// <summary>
    /// Forgets pushes, whether they were answered or have simply expired.
    /// </summary>
    /// <param name="ticketIds">The ticket ids to drop.</param>
    public void RemoveExpoReceipts(IEnumerable<string> ticketIds)
    {
        ArgumentNullException.ThrowIfNull(ticketIds);

        var ids = ticketIds.Distinct(StringComparer.Ordinal).ToList();
        if (ids.Count == 0)
        {
            return;
        }

        using var context = CreateContext();

        var rows = context.ExpoReceipts.Where(r => ids.Contains(r.TicketId)).ToList();
        if (rows.Count == 0)
        {
            return;
        }

        context.ExpoReceipts.RemoveRange(rows);
        context.SaveChanges();
    }

    /// <summary>
    /// Forgets pushes Expo would no longer answer for.
    /// </summary>
    /// <param name="sentBefore">Only pushes older than this, in UTC.</param>
    /// <returns>How many rows were dropped.</returns>
    /// <remarks>
    /// Expo keeps a receipt for 24 hours. Past that the answer is never coming, and a row
    /// that is never removed is the same accumulation in a different table.
    /// </remarks>
    public int RemoveExpoReceiptsSentBefore(DateTime sentBefore)
    {
        using var context = CreateContext();

        var rows = context.ExpoReceipts.Where(r => r.CreatedAt <= sentBefore).ToList();
        if (rows.Count == 0)
        {
            return 0;
        }

        context.ExpoReceipts.RemoveRange(rows);
        context.SaveChanges();

        return rows.Count;
    }

    /// <summary>
    /// Removes every device token.
    /// </summary>
    public void Purge()
    {
        using var context = CreateContext();
        context.DeviceTokens.RemoveRange(context.DeviceTokens);
        context.SaveChanges();
    }

    /// <summary>
    /// Reads the configuration the server declares for everyone.
    /// </summary>
    /// <returns>The stored JSON, or <c>null</c> before anything has been written.</returns>
    public string? GetGlobalConfigJson()
    {
        using var context = CreateContext();
        return context.GlobalConfigurations.AsNoTracking()
            .FirstOrDefault(c => c.Id == GlobalConfiguration.Current)?.ConfigJson;
    }

    /// <summary>
    /// Writes the configuration the server declares for everyone.
    /// </summary>
    /// <param name="configJson">The configuration, as JSON.</param>
    public void SaveGlobalConfigJson(string configJson)
    {
        using var context = CreateContext();

        var existing = context.GlobalConfigurations
            .FirstOrDefault(c => c.Id == GlobalConfiguration.Current);

        if (existing is null)
        {
            context.GlobalConfigurations.Add(new GlobalConfiguration
            {
                Id = GlobalConfiguration.Current,
                ConfigJson = configJson
            });
        }
        else
        {
            existing.ConfigJson = configJson;
        }

        context.SaveChanges();
    }

    /// <summary>
    /// Carries the configuration over from Jellyfin's plugin XML, once.
    /// </summary>
    /// <param name="configJson">The configuration as it stands in the XML, as JSON.</param>
    /// <returns>True when this call performed the import.</returns>
    /// <remarks>
    /// Same shape as the device token import: a marker written in the same transaction
    /// as the row, so a failure leaves neither and the next start retries. The XML file
    /// is never written to and never deleted, so downgrading to a build that reads it
    /// finds it exactly as it was left.
    /// </remarks>
    public bool ImportGlobalConfiguration(string configJson)
    {
        using var context = CreateContext();

        if (context.ImportMarkers.Any(m => m.Name == ImportMarker.LegacyGlobalConfig))
        {
            return false;
        }

        context.GlobalConfigurations.Add(new GlobalConfiguration
        {
            Id = GlobalConfiguration.Current,
            ConfigJson = configJson
        });

        context.ImportMarkers.Add(new ImportMarker
        {
            Name = ImportMarker.LegacyGlobalConfig,
            ImportedAt = DateTimeOffset.UtcNow,
            RowsImported = 1
        });

        context.SaveChanges();
        return true;
    }

    /// <summary>
    /// Gets every settings group.
    /// </summary>
    /// <returns>The groups, in layer order.</returns>
    public List<SettingsGroup> GetSettingsGroups()
    {
        using var context = CreateContext();
        return SettingsResolver.InLayerOrder(context.SettingsGroups.AsNoTracking().ToList()).ToList();
    }

    /// <summary>
    /// Gets one settings group.
    /// </summary>
    /// <param name="id">The group id.</param>
    /// <returns>The group, or <c>null</c> when there is no such group.</returns>
    public SettingsGroup? GetSettingsGroup(Guid id)
    {
        using var context = CreateContext();
        return context.SettingsGroups.AsNoTracking().FirstOrDefault(g => g.Id == id);
    }

    /// <summary>
    /// Creates or updates a settings group.
    /// </summary>
    /// <param name="group">The group. An empty id means create.</param>
    /// <returns>The stored group, with its id.</returns>
    public SettingsGroup SaveSettingsGroup(SettingsGroup group)
    {
        ArgumentNullException.ThrowIfNull(group);

        using var context = CreateContext();

        if (group.Id == Guid.Empty)
        {
            group.Id = Guid.NewGuid();
            context.SettingsGroups.Add(group);
        }
        else
        {
            var existing = context.SettingsGroups.FirstOrDefault(g => g.Id == group.Id);
            if (existing is null)
            {
                context.SettingsGroups.Add(group);
            }
            else
            {
                existing.Name = group.Name;
                existing.Priority = group.Priority;
                existing.SettingsJson = group.SettingsJson;
            }
        }

        context.SaveChanges();
        return group;
    }

    /// <summary>
    /// Deletes a settings group and everyone's membership of it.
    /// </summary>
    /// <param name="id">The group id.</param>
    /// <remarks>
    /// Both in one transaction. A group deleted while its memberships survive would
    /// leave rows that resolve to nothing and reappear if the id were ever reused.
    /// </remarks>
    public void RemoveSettingsGroup(Guid id)
    {
        using var context = CreateContext();

        var existing = context.SettingsGroups.FirstOrDefault(g => g.Id == id);
        if (existing is null)
        {
            return;
        }

        context.SettingsGroupMembers.RemoveRange(
            context.SettingsGroupMembers.Where(m => m.GroupId == id));
        context.SettingsGroups.Remove(existing);
        context.SaveChanges();
    }

    /// <summary>
    /// Gets the members of a group.
    /// </summary>
    /// <param name="groupId">The group id.</param>
    /// <returns>The Jellyfin user ids.</returns>
    public List<Guid> GetGroupMembers(Guid groupId)
    {
        using var context = CreateContext();
        return context.SettingsGroupMembers.AsNoTracking()
            .Where(m => m.GroupId == groupId)
            .Select(m => m.UserId)
            .ToList();
    }

    /// <summary>
    /// Replaces the membership of a group.
    /// </summary>
    /// <param name="groupId">The group id.</param>
    /// <param name="userIds">Who should be in it afterwards.</param>
    public void SetGroupMembers(Guid groupId, IEnumerable<Guid> userIds)
    {
        using var context = CreateContext();

        context.SettingsGroupMembers.RemoveRange(
            context.SettingsGroupMembers.Where(m => m.GroupId == groupId));

        foreach (var userId in (userIds ?? []).Distinct())
        {
            context.SettingsGroupMembers.Add(new SettingsGroupMember
            {
                GroupId = groupId,
                UserId = userId
            });
        }

        context.SaveChanges();
    }

    /// <summary>
    /// Gets the groups a user belongs to.
    /// </summary>
    /// <param name="userId">The Jellyfin user id.</param>
    /// <returns>The groups, least specific first.</returns>
    public List<SettingsGroup> GetGroupsForUser(Guid userId)
    {
        using var context = CreateContext();

        var groups = context.SettingsGroupMembers.AsNoTracking()
            .Where(m => m.UserId == userId)
            .Join(
                context.SettingsGroups.AsNoTracking(),
                m => m.GroupId,
                g => g.Id,
                (_, g) => g)
            .ToList();

        return SettingsResolver.InLayerOrder(groups).ToList();
    }

    /// <summary>
    /// Gets the settings targeted at one user.
    /// </summary>
    /// <param name="userId">The Jellyfin user id.</param>
    /// <returns>The override, or <c>null</c> when there is none.</returns>
    public UserSettingsOverride? GetUserSettingsOverride(Guid userId)
    {
        using var context = CreateContext();
        return context.UserSettingsOverrides.AsNoTracking()
            .FirstOrDefault(o => o.UserId == userId);
    }

    /// <summary>
    /// Replaces every targeting level in one go.
    /// </summary>
    /// <param name="groups">The groups to keep, each with its members.</param>
    /// <param name="overrides">The settings targeted at one user each.</param>
    /// <remarks>
    /// One transaction, because half of this is worse than none of it. A restore that
    /// deleted every group and then failed on the third one it was writing back would
    /// leave a server with neither what it had nor what the file carried.
    /// </remarks>
    public void ReplaceTargeting(
        IEnumerable<(SettingsGroup Group, IReadOnlyList<Guid> Members)> groups,
        IEnumerable<(Guid UserId, string SettingsJson)> overrides)
    {
        ArgumentNullException.ThrowIfNull(groups);
        ArgumentNullException.ThrowIfNull(overrides);

        using var context = CreateContext();
        using var transaction = context.Database.BeginTransaction();

        context.SettingsGroupMembers.RemoveRange(context.SettingsGroupMembers);
        context.SettingsGroups.RemoveRange(context.SettingsGroups);
        context.UserSettingsOverrides.RemoveRange(context.UserSettingsOverrides);
        context.SaveChanges();

        foreach (var (group, members) in groups)
        {
            // The id the file carries, so restoring one onto the server it came from
            // changes nothing: groups sharing a priority are ordered by id, and a fresh
            // one would silently reorder them.
            group.Id = group.Id == Guid.Empty ? Guid.NewGuid() : group.Id;
            context.SettingsGroups.Add(group);

            foreach (var member in members.Distinct())
            {
                context.SettingsGroupMembers.Add(new SettingsGroupMember
                {
                    GroupId = group.Id,
                    UserId = member
                });
            }
        }

        foreach (var (userId, settingsJson) in overrides)
        {
            context.UserSettingsOverrides.Add(new UserSettingsOverride
            {
                UserId = userId,
                SettingsJson = settingsJson
            });
        }

        context.SaveChanges();
        transaction.Commit();
    }

    /// <summary>
    /// Every user who has settings targeted at them.
    /// </summary>
    /// <returns>The overrides, one per user.</returns>
    public List<UserSettingsOverride> GetAllUserSettingsOverrides()
    {
        using var context = CreateContext();
        return context.UserSettingsOverrides.AsNoTracking().ToList();
    }

    /// <summary>
    /// Sets the settings targeted at one user.
    /// </summary>
    /// <param name="userId">The Jellyfin user id.</param>
    /// <param name="settingsJson">A partial set of settings, as JSON.</param>
    public void SaveUserSettingsOverride(Guid userId, string settingsJson)
    {
        using var context = CreateContext();

        var existing = context.UserSettingsOverrides.FirstOrDefault(o => o.UserId == userId);
        if (existing is null)
        {
            context.UserSettingsOverrides.Add(new UserSettingsOverride
            {
                UserId = userId,
                SettingsJson = settingsJson
            });
        }
        else
        {
            existing.SettingsJson = settingsJson;
        }

        context.SaveChanges();
    }

    /// <summary>
    /// Clears the settings targeted at one user.
    /// </summary>
    /// <param name="userId">The Jellyfin user id.</param>
    public void RemoveUserSettingsOverride(Guid userId)
    {
        using var context = CreateContext();

        var existing = context.UserSettingsOverrides.FirstOrDefault(o => o.UserId == userId);
        if (existing is null)
        {
            return;
        }

        context.UserSettingsOverrides.Remove(existing);
        context.SaveChanges();
    }

    /// <summary>
    /// Carries device tokens over from the hand written store, once.
    /// </summary>
    /// <remarks>
    /// Failure is not fatal. A server that cannot read the old file still starts,
    /// keeps working with an empty table, and tries again next time, which is the
    /// only acceptable behaviour for something that runs during plugin activation.
    /// </remarks>
    /// <param name="context">An open context on the new database.</param>
    private void ImportLegacyDeviceTokens(StreamyfinDbContext context)
    {
        if (context.ImportMarkers.Any(m => m.Name == ImportMarker.LegacyDeviceTokens))
        {
            return;
        }

        if (!File.Exists(LegacyDbFilePath))
        {
            MarkImported(context, 0);
            return;
        }

        List<DeviceToken> legacy;
        try
        {
            legacy = LegacyDeviceTokenReader.Read(LegacyDbFilePath);
        }
        catch (Exception ex)
        {
            _logger?.LogWarning(
                ex,
                "Could not read the previous database at {Path}. Device tokens were not imported and the import will be retried on the next start",
                LegacyDbFilePath);
            return;
        }

        try
        {
            var known = context.DeviceTokens.Select(t => t.DeviceId).ToHashSet();
            var fresh = legacy.Where(t => !known.Contains(t.DeviceId)).ToList();

            using var transaction = context.Database.BeginTransaction();
            context.DeviceTokens.AddRange(fresh);
            context.ImportMarkers.Add(new ImportMarker
            {
                Name = ImportMarker.LegacyDeviceTokens,
                ImportedAt = DateTimeOffset.UtcNow,
                RowsImported = fresh.Count
            });
            context.SaveChanges();
            transaction.Commit();

            _logger?.LogInformation(
                "Imported {Count} device token(s) from {Path}. The old file is left in place and is not read again",
                fresh.Count,
                LegacyDbFilePath);
        }
        catch (Exception ex)
        {
            _logger?.LogWarning(
                ex,
                "Could not import device tokens from {Path}. The import will be retried on the next start",
                LegacyDbFilePath);
        }
    }

    private static void MarkImported(StreamyfinDbContext context, int rows)
    {
        context.ImportMarkers.Add(new ImportMarker
        {
            Name = ImportMarker.LegacyDeviceTokens,
            ImportedAt = DateTimeOffset.UtcNow,
            RowsImported = rows
        });
        context.SaveChanges();
    }
}
