// <auto-generated />
using System;
using Jellyfin.Plugin.Streamyfin.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jellyfin.Plugin.Streamyfin.Migrations
{
    [DbContext(typeof(StreamyfinDbContext))]
    [Migration("20260824150644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Jellyfin.Plugin.Streamyfin.Db.DeviceToken", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId");

                    b.HasIndex("UserId");

                    b.ToTable("DeviceTokens", (string)null);
                });

            modelBuilder.Entity("Jellyfin.Plugin.Streamyfin.Db.ImportMarker", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RowsImported")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("ImportMarkers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
